### ISSUE TITLE
Getting Problem starting the module mod_offline_post for host "127.0.0.1" error

### ISSUE THREAD

**Issue by vkrm26** [adamvduke/mod_interact#14]
Hi,
Could you please tell me how to resolve following error ?
Though I'm able to build it properly.
and please enlighten what to use as auth_token?

Problem starting the module mod_offline_post for host "127.0.0.1" 
 options: [{auth_token,"your-secret-token-here"},
           {post_url,"http://www.*****.com:8080/temp_server/"}]
 error: badarg

Thanks a lot.

**Comment by adamvduke** [comment]
I haven't used this module in production for some time and the ejabberd ecosystem has continued evolving. I would use the module as a getting started point and accept that you will likely have to make code changes to get things working as expected. Additionally, you might find other [open issues or pull requests](https://github.com/adamvduke/mod_interact/issues?utf8=%E2%9C%93&q=is%3Aopen+) that solve some problems. I unfortunately can't offer support at this time.

**Comment by vkrm26** [comment]
Thank you so much ! It worked for me. I was confused for secret token.
If some one stucks at this problem, Lemme know.
