### ISSUE TITLE
error: undef {p1_logger,info_msg,[mod_offline_post,45,"Starting mod_offline_post",[]],[]}

### ISSUE THREAD

**Issue by kmaxat** [adamvduke/mod_interact#2]
There seems to be an issue with eJabberd 13.12. Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:true]
Do you have any idea how to solve that?

**Comment by adamvduke** [comment]
There are some incompatibility issues depending on what headers and/or binaries are available during compile with eJabberd 13.12.

So far the solution has been to remove the lines containing the ?INFO_MSG macro.

I'll leave this open until I have time to properly address the compilation with the new ejabberd version and can provide a more step by step walk through to allow the logging to stay in place.

**Comment by adamvduke** [comment]
@kmaxat ^^

**Comment by kmaxat** [comment]
Hi! I haven't actually used it, but it seems that the issue has been solved. Look:
https://github.com/processone/ejabberd-contrib/issues/13
Don't worry about solving. I will do it.

**Comment by kuryaki** [comment]
this solved it for me http://chatlogs.jabber.ru/ejabberd@conference.jabber.ru/2013/11/22.html
